name: Feature Enhancement
description: Suggest an improvement to an existing feature / 改进现有功能
title: "[Feature Enhancement]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        This template is for suggesting improvements to existing features only.
        If you are requesting a new feature, please use the Feature Request template.

        此模板仅用于提出对现有功能的改进建议。如果是全新的功能需求，请使用 Feature 模板。

  - type: input
    id: version
    attributes:
      label: Version / 版本
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior / 当前结果
      description: How does the feature work now? / 当前功能是如何工作的？
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Insufficient / 问题或不足
      description: What is inconvenient or insufficient? / 有哪些不便或不足之处？
    validations:
      required: true

  - type: textarea
    id: enhancement
    attributes:
      label: Enhancement Case / 改进方案
      description: How should it be improved? / 如何改进？
      placeholder: |
           e.g. Describe expected behavio of the feature in detail.
           例：请详细描述该功能的期望行为。
    validations:
      required: true
