export const VFS_CONSTANTS = Object.freeze({
  //注意常量大小写问题
  CURRENT_WORKSPACE_NAME: 'Snaptium',
  PREFERENCES_FILE: 'preferences.json',
  NOTE_SAVE_PATH_KEY: 'noteSavePath',
  USER_DATA: 'userData',
  DOCUMENTS_FOLDER: 'documents',
  DATABASE_FOLDER: 'Database',
  OBJECTS_FOLDER: 'objects',
  IMAGES_FOLDER: 'images',
  TRASH_FOLDER: 'trash',
  NODES_FILE: 'nodes.jsonl',
  META_FILE: 'meta.json',
  HISTORY_FOLDER: 'history',
  NODE_TYPE_FILE: 'file',
  NODE_TYPE_FOLDER: 'folder',
  MARKDOWN_FILE_EXT: '.md',
  JSON_FILE_EXT: '.json',
  TEMP_FILE_EXT: '.tmp',
  FIELD_CONTENT_ID: 'contentId',
  FIELD_NODE_ID: 'nodeId',
  BACKUP_FILE_EXT: '.bak',
  NOTE_TYPE_EXE: 'exe',
});
